### ISSUE TITLE
projekt GUI

### ISSUE THREAD

**Issue by KKeelloo** [KKeelloo/text-transformer#33]

**Comment by matyldv** [comment]
![gui](https://user-images.githubusercontent.com/73503512/104912716-ebb91180-598c-11eb-9da7-06c37f377774.PNG)

**Comment by matyldv** [comment]
![gui](https://user-images.githubusercontent.com/73503512/104913702-4bfc8300-598e-11eb-8716-6716b3c46920.PNG)
